### DISCUSSION TITLE
Api call ro set and activate climate temp?

### DISCUSSION THREAD

**Discussion by Jurgen-DOUCHY** [dahlb/ha_kia_hyundai#127] [Q&A] [answered]
Don't know if this would be possible.
But it would be very handy to be able to activate and set the climate temp trough the integration.
That way we can make automations. :)

**Comment by dahlb** [comment, marked as answer]
already a feature, see example call below

```
service: ha_kia_hyundai.start_climate
data:
  climate: true
  defrost: true
  heating: true
  temperature: "76"
```
