### ISSUE TITLE
support celsius in service definitions

### ISSUE THREAD

**Issue by dahlb** [dahlb/ha_kia_hyundai#38]
Hoping the services.yml can be defined dynamically to better service different units in HA.

**Comment by dahlb** [comment]
something like this might work
```
        hass.services.async_register(
            DOMAIN,
            SERVICE_HUE_ACTIVATE_SCENE,
            verify_domain_control(hass, DOMAIN)(hue_activate_scene),
            schema=vol.Schema(
                {
                    vol.Required(ATTR_GROUP_NAME): cv.string,
                    vol.Required(ATTR_SCENE_NAME): cv.string,
                    vol.Optional(ATTR_TRANSITION): cv.positive_int,
                    vol.Optional(ATTR_DYNAMIC): cv.boolean,
                }
            ),
        )
```
to handle different ranges dynamically

```

hue_activate_scene:
  name: Activate scene
  description: Activate a hue scene stored in the hue hub.
  fields:
    group_name:
      name: Group
      description: Name of hue group/room from the hue app.
      example: "Living Room"
      selector:
        text:
    scene_name:
      name: Scene
      description: Name of hue scene from the hue app.
      example: "Energize"
      selector:
        text:
    dynamic:
      name: Dynamic
      description: Enable dynamic mode of the scene (V2 bridges and supported scenes only).
      selector:
        boolean:
```
