### ISSUE TITLE
issue to connect

### ISSUE THREAD

**Issue by olivierjag2** [dahlb/ha_kia_hyundai#43]
when I try to connect the integration, with kia ou Hyundai canada (I have both car) I have this error

![image](https://user-images.githubusercontent.com/31319364/147369507-f4bc7170-f230-45e7-9271-82d5703a35f4.png)

**Comment by dahlb** [comment]
@olivierjag2 thanks for filing this ticket about the trouble you're having.  It makes sense the kia and hyundai errors are the same they are nearly identical code within the CA region.

can you try it again after enabling debug logging for this integration

To enable logging, update your configuration.yaml like this, we can get more information in Configuration -> Logs page

```
logger:
  default: warning
  logs:
    custom_components.ha_kia_hyundai: debug
    kia_hyundai_api: debug
```

then attach/paste here the logs generated during the configuration flow. _**be_sure to remove the credentials from the logs you share**_

I am US/Kia so I haven't been able to test those code paths yet; but it is likely a simple typo I can fix within a few hours with the logs.
